def main() -> None: ...
def listContents(elemlist, resolve): ...
def listShaderBindings(shader): ...
def listNodedefInterface(nodedef): ...
def traverseInputs(node, port, depth): ...
def pl(elem): ...
def spc(depth): ...
def getConvertedValue(elem): ...
def getGeoms(elem, resolve): ...
def getViewerGeoms(elem): ...
def getTarget(elem): ...
